### ISSUE TITLE
Access policy - ToS

### ISSUE THREAD

**Issue by unknowndevice** [Inboxen/infrastructure#21]
What kind of policy does Inboxen have for accessing my account? Under what kind of circumstance would the account be accessed? As someone who's interested in using the service, I'm turned off using it because I don't know how private my data is.

Maybe a ToS or access policy should be written up. (Maybe get the ToS put on tosdr.org)

**Comment by moggers87** [comment]
https://github.com/Inboxen/Inboxen/issues/162
